export const PLEDGES = [
  {
    title: "Energy Conservation",
    image: "/pledges/energy.png",
    theme: "from-blue-400 via-blue-500 to-orange-400",
    description: "Commit to using renewable energy sources",
  },
  {
    title: "Water Conservation",
    image: "/pledges/water.png",
    theme: "from-gray-100 via-blue-100 to-gray-200",
    description: "Pledge to protect our water resources",
  },
  {
    title: "Plastic Reduction",
    image: "/pledges/plastic.png",
    theme: "from-amber-100 via-amber-50 to-amber-200",
    description: "Reduce single-use plastic consumption",
  },
  {
    title: "Sustainable Transport",
    image: "/pledges/transport.png",
    theme: "from-yellow-200 via-amber-300 to-orange-400",
    description: "Choose eco-friendly transportation",
  },
  {
    title: "Recycling",
    image: "/pledges/recycle.png",
    theme: "from-green-100 via-emerald-100 to-green-200",
    description: "Commit to proper waste recycling",
  },
  {
    title: "Plant Trees",
    image: "/pledges/plant.png",
    theme: "from-gray-50 via-green-50 to-gray-100",
    description: "Support reforestation efforts",
  },
  {
    title: "Renewable Energy",
    image: "/pledges/renewable.png",
    theme: "from-teal-200 via-green-300 to-yellow-300",
    description: "Invest in clean energy solutions",
  },
  {
    title: "Wildlife Protection",
    image: "/pledges/wildlife.png",
    theme: "from-green-400 to-green-600",
    description: "Protect endangered species",
  },
  {
    title: "Ocean Conservation",
    image: "/pledges/ocean.png",
    theme: "from-blue-300 to-teal-500",
    description: "Preserve marine ecosystems",
  },
  {
    title: "Sustainable Living",
    image: "/pledges/sustainanle.png",
    theme: "from-emerald-300 to-green-500",
    description: "Adopt sustainable daily practices",
  },
]

export const getAchievementContent = (index: number) => {
  const achievements = [
    {
      title: "Energy Guardian",
      subtitle: "Renewable Energy Champion",
      message: "You've committed to sustainable power solutions and clean energy adoption.",
      icon: "⚡",
      impact: "2,400 kWh saved annually",
      badge: "ENERGY SAVER",
      color: "from-blue-400 via-blue-500 to-orange-400",
    },
    {
      title: "Water Protector",
      subtitle: "Aquatic Life Guardian",
      message: "You're now a guardian of our precious water resources and marine ecosystems.",
      icon: "💧",
      impact: "10,000 liters conserved yearly",
      badge: "WATER GUARDIAN",
      color: "from-gray-100 via-blue-100 to-gray-200",
    },
    {
      title: "Plastic Warrior",
      subtitle: "Waste Reduction Hero",
      message: "You've joined the fight against single-use plastics and environmental pollution.",
      icon: "♻️",
      impact: "500+ plastic items prevented",
      badge: "ECO WARRIOR",
      color: "from-amber-100 via-amber-50 to-amber-200",
    },
    {
      title: "Green Commuter",
      subtitle: "Sustainable Transport Advocate",
      message: "You've chosen eco-friendly transportation for a cleaner planet.",
      icon: "🚲",
      impact: "1.2 tons CO2 reduced annually",
      badge: "GREEN TRAVELER",
      color: "from-yellow-200 via-amber-300 to-orange-400",
    },
    {
      title: "Recycling Champion",
      subtitle: "Circular Economy Leader",
      message: "You're committed to proper waste management and resource recovery.",
      icon: "🔄",
      impact: "80% waste diverted from landfills",
      badge: "RECYCLING HERO",
      color: "from-green-100 via-emerald-100 to-green-200",
    },
    {
      title: "Tree Planter",
      subtitle: "Forest Restoration Hero",
      message: "You've pledged to support reforestation and biodiversity preservation.",
      icon: "🌱",
      impact: "48 lbs CO2 absorbed per tree yearly",
      badge: "FOREST GUARDIAN",
      color: "from-gray-50 via-green-50 to-gray-100",
    },
    {
      title: "Clean Energy Advocate",
      subtitle: "Renewable Future Builder",
      message: "You're investing in sustainable energy solutions for tomorrow.",
      icon: "☀️",
      impact: "Clean energy adoption accelerated",
      badge: "ENERGY PIONEER",
      color: "from-teal-200 via-green-300 to-yellow-300",
    },
    {
      title: "Wildlife Guardian",
      subtitle: "Species Protection Champion",
      message: "You've committed to protecting endangered species and their habitats.",
      icon: "🐅",
      impact: "Biodiversity preservation supported",
      badge: "WILDLIFE PROTECTOR",
      color: "from-green-400 to-green-600",
    },
    {
      title: "Ocean Defender",
      subtitle: "Marine Conservation Hero",
      message: "You're protecting our oceans and marine life for future generations.",
      icon: "🌊",
      impact: "Marine ecosystems preserved",
      badge: "OCEAN GUARDIAN",
      color: "from-blue-300 to-teal-500",
    },
    {
      title: "Sustainability Leader",
      subtitle: "Lifestyle Change Champion",
      message: "You've embraced sustainable practices that inspire others to act.",
      icon: "🌍",
      impact: "Sustainable lifestyle adopted",
      badge: "ECO LEADER",
      color: "from-emerald-300 to-green-500",
    },
  ]
  return achievements[index] || achievements[0]
}
